stages:
    - build_dockers
    - test
    - deploy
    - documentation

dockers:
    stage: build_dockers
    when: manual
    tags:
        - ci.inria.fr
        - small
    image: docker:stable
    script:
        - docker build -t "$CI_REGISTRY_IMAGE/xllim_runner" --target runner .
        - docker build -t "$CI_REGISTRY_IMAGE/xllim_builder" --target builder .
        # - docker build -f Builder.dockerfile -t "$CI_REGISTRY_IMAGE/kernelo_coverage" --target coveragetester .
        - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
        - docker push "$CI_REGISTRY_IMAGE/xllim_runner"
        - docker push "$CI_REGISTRY_IMAGE/xllim_builder"
        # - docker push "$CI_REGISTRY_IMAGE/kernelo_coverage"

deploy_docker:
    stage: deploy
    when: manual
    tags:
        - ci.inria.fr
        - small
    image: docker:stable
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - apk update
        - apk add curl
        - 'curl --location --output artefact_token.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://gitlab.inria.fr/api/v4/projects/kernelo-mistis%2Fkernelo-gllim-is/jobs/artifacts/v2/download?job=build_job"'
        - ls
        - cat artefact_token.zip
        - curl --location --output artefact.zip "https://gitlab.inria.fr/api/v4/projects/kernelo-mistis%2Fkernelo-gllim-is/jobs/artifacts/v2/download?job=build_job"
        - ls
        - cat artefact.zip
        - unzip artefact.zip
        - rm artefact.zip
        # - docker build --no-cache --build-arg image=$CI_REGISTRY_IMAGE/xllim_runner:latest -f minimal.Dockerfile -t $CI_REGISTRY_IMAGE/xllim_minimal:$CI_COMMIT_BRANCH .
        # - docker push $CI_REGISTRY_IMAGE/xllim_minimal:$CI_COMMIT_BRANCH
        - docker pull $CI_REGISTRY_IMAGE/xllim_runner
        - docker run -it -d --rm --name xllim_minimal_temp_container $CI_REGISTRY_IMAGE/xllim_runner
        - docker cp *.so xllim_minimal_temp_container:/usr/lib/python3/dist-packages/xllim.so
        - docker commit xllim_minimal_temp_container $CI_REGISTRY_IMAGE/xllim_minimal
        - docker stop xllim_minimal_temp_container
        - docker push "$CI_REGISTRY_IMAGE/xllim_minimal"

test_job:
    stage: test
    when: manual
    tags:
        - ci.inria.fr
        - small
    image: "$CI_REGISTRY_IMAGE/xllim_builder"
    script:
        - apt-get update
        - apt-get install -y --no-install-recommends git
        - git submodule init
        - git submodule update
        - git submodule
        - rm -rf build && mkdir build && cd build
        # On est censé build ici et dans build_job... redondant !
        - cmake -S .. -B . -DPYTHON_LIBRARY_DIR="$(pwd)/.." -DCMAKE_BUILD_TYPE=Release
        - make install
        - ctest

build_job:
    stage: deploy
    when: manual
    artifacts:
        paths:
            - xllim*.so
    tags:
        - ci.inria.fr
        - small
    image: "$CI_REGISTRY_IMAGE/xllim_builder"
    script:
        - apt-get update
        - apt-get install -y --no-install-recommends git
        - git submodule init
        - git submodule update
        - git submodule
        - rm -rf build && mkdir build && cd build
        - cmake -S .. -B . -DPYTHON_LIBRARY_DIR="$(pwd)/.." -DCMAKE_BUILD_TYPE=Release
        - make install

pages:
    stage: documentation
    when: manual
    tags:
        - ci.inria.fr
        - small
    image: "$CI_REGISTRY_IMAGE/xllim_builder"
    script:
        - pip install -U sphinx sphinx-rtd-theme myst_parser sphinx-copybutton
        - sphinx-build -b html docs/sphinx/source public
    artifacts:
        paths:
            - public
