build-wheels:
  stage: package
  when: manual
  image: python:3.11
  tags:
    - ci.inria.fr
    - small
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends docker.cli
    - pip install --upgrade pip
    - pip install cibuildwheel
    - pip install auditwheel
  script:
    - cibuildwheel --output-dir wheelhouse
    - auditwheel show wheelhouse/*.whl
  artifacts:
    paths:
      - wheelhouse/*.whl
    expire_in: 1 week
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
    # Install all necessary dependancies in cibuildwheel conatiners
    # epl-release : for access at Armadillo
    CIBW_BEFORE_ALL_LINUX: >
      dnf install -y epel-release &&
      dnf module enable -y boost:1.76 &&
      dnf install -y
      boost-devel
      blas-devel
      lapack-devel
      armadillo-devel
    CIBW_BUILD: "cp31*-manylinux_x86_64"
    CIBW_SKIP: "*-musllinux_*"
