# url of the SonarQube server
sonar.host.url=https://sonarqube.inria.fr/sonarqube
# login/password mechanism required to transmit the analysis to the sonarqube server (password must be left empty with the token usage)
sonar.login=a5bb66387ab78f73250862bdf152449cbf5a4918
# must be unique in a given SonarQube instance
sonar.projectKey=statify:kenrelo-gllim-is
# used to compare metrics with v1.10 for example
# sonar.projectVersion=1.11
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.
sonar.tests=cpptest
# exclude some files from being analyzed
sonar.exclusions=build/CMakeFiles/**,cmake/**,doc/**,extern/**,cpptest/**
# clarify what is c and c++ files
sonar.lang.patterns.c++=**/*.cpp,**/*.hpp,**/*.tpp
sonar.lang.patterns.c=**/*.c,**/*.h
# external analysis tools reports
sonar.c.gcc.charset=UTF-8
sonar.c.gcc.regex=(?<file>.*):(?<line>[0-9]+):[0-9]+:\\\x20warning:\\\x20(?<message>.*)\\\x20\\\[(?<id>.*)\\\]
sonar.c.gcc.reportPath=build/build.log
#sonar.c.clangsa.reportPath=build/analyzer_reports/*/*.plist
#sonar.c.clangtidy.reportPath=clang-tidy-report
#sonar.c.coverage.reportPath=build/coverage.xml
sonar.coverageReportPaths=build/coverage.xml
#sonar.cxx.cobertura.reportPaths=build/coverage.xml
#sonar.c.cppcheck.reportPath=cppcheck.xml
#sonar.c.rats.reportPath=rats.xml
#sonar.c.vera.reportPath=vera.xml
#sonar.c.valgrind.reportPath=valgrind.xml
#sonar.c.drmemory.reportPath=drmemory/**/results.txt
