# url of the SonarQube server
sonar.host.url=https://sonarqube.inria.fr/sonarqube

# login/password mechanism required to transmit the analysis to the sonarqube 
sonar.login=1469b2e4a13a98c4db0fbb7c98f9c1e221eb1140

# must be unique in a given SonarQube instance
sonar.projectKey=mistis:kernelo:binding:v0.1

# used to compare metrics with v1.10 for example
sonar.projectVersion=1.11

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=./src

# Source code language
sonar.language=c++
