sonar.projectKey=xllim-tools_xllim
sonar.organization=xllim-tools

sonar.sources=src,xllim,bindings
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage-python.xml
sonar.coverageReportPaths=coverage-cpp.xml

sonar.python.version= 3.11, 3.12