{% set name = "xllim" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.18
    - ninja
    - make
    - git

  host:
    - python >=3.11
    - pip
    - setuptools >=42
    - wheel
    - scikit-build-core >=0.7.0
    - numpy >=1.21
    - boost
    - libblas * *openblas
    - liblapack * *openblas
    - openblas
    - armadillo 14.4.3

  run:
    - python >=3.11
    - numpy >=1.21
    - h5py
    - openblas >=0.3.29
    - libstdcxx-ng  # [linux]

test:
  imports:
    - xllim
    - xllim._core
    - xllim.cli
    - xllim.utils
  commands:
    - xllim_cli --help
  requires:
    - pip
  source_files:
    - tests/

about:
  home: https://gitlab.inria.fr/xllim
  license: CeCILL-C
  license_file: LICENCE.txt
  summary: 'Python package for XLLiM with C++ core'
  description: |
    xLLiM is a C++ with Python bindings implementation of Gaussian Locally-Linear Mapping. It can be used to perform efficient inversion of high-dimensional models.
  doc_url: https://xllim.gitlabpages.inria.fr/xllim/index.html
  dev_url: https://gitlab.inria.fr/xllim

anaconda_upload: False